yarnPath: '.yarn/releases/yarn-berry.cjs'
nodeLinker: node-modules
packageExtensions:
  'next@9.5.2':
    dependencies:
      caniuse-lite: '^1.0.30001019'
  'mobx-react@6.1.8':
    dependencies:
      react-dom: '16.13.1'
  'apollo-server-micro@2.11.0':
    peerDependencies:
      graphql-tools: '*'
      graphql: '*'
  'apollo-datasource-rest@0.8.0':
    peerDependencies:
      graphql: '*'
  'react-styleguidist@11.0.6':
    peerDependencies:
      webpack: '^4.0.0'
  'next-images@1.4.1':
    peerDependencies:
      webpack: '^4.0.0'
  'sass-resources-loader@2.1.0':
    dependencies:
      '@babel/core': '^7.0.0'
    peerDependencies:
      eslint: '>= 4.12.1'
  '@zeit/next-css@1.0.1':
    peerDependencies:
      webpack: '^4.4.0'
  '@zeit/next-sass@1.0.1':
    peerDependencies:
      webpack: '^3.0.0'
  '@apollo/client@3.1.3':
    dependencies:
      react-dom: '16.13.1'
  '@apollographql/apollo-tools@0.4.3':
    peerDependencies:
      graphql: '*'
  '@graphql-tools/links@6.2.0':
    dependencies:
      subscriptions-transport-ws: '^0.9.0'
